kind = "web"
previewPath = "/"
title = "Nermeen's Recipe Book"
version = "1.0.0"
id = "recipe-book-flask-app"

[[services]]
localPort = 5000
name = "Recipe Book"
paths = ["/"]

[services.env]
PORT = "5000"

[services.development]
run = "pip install flask markdown gunicorn --quiet && gunicorn --bind 0.0.0.0:$PORT --reuse-port --reload --chdir /home/runner/workspace/artifacts/recipe-book app:app"

[services.production]

[services.production.build]
args = ["echo", "no-build"]

[services.production.run]
args = ["sh", "-c", "pip install flask markdown gunicorn --quiet && gunicorn --bind 0.0.0.0:$PORT --workers 2 --chdir /home/runner/workspace/artifacts/recipe-book app:app"]
